Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectZero.Models;
using ProjectZero.Services;

namespace ProjectZero.Controllers {
    public class AuthorsController : Controller {

        private readonly IAuthorService _service;
        private readonly IAuthorBookConnectionService _service2;
        public AuthorsController (IAuthorService service, IAuthorBookConnectionService service2) {
            this._service = service;
            this._service2 = service2;
        }

        public IActionResult Index() {
            return View(this._service.ShowAuthors());
        }

        [HttpPost]
        public IActionResult AddAuthor(AuthorModel newAuthor) {
            this._service.AddAuthor(newAuthor);
            return RedirectToAction("Index");
        }

        public IActionResult RemoveAuthor(int removedAuthor) {
            this._service.RemoveAuthor(removedAuthor);
            return RedirectToAction("Index");
        }
    }
}

Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectZero.Models;
using ProjectZero.Services;

namespace ProjectZero.Controllers {
    public class BooksController : Controller {
        private readonly IBookService _service;
        public BooksController (IBookService service) {
            this._service = service;
        }

        public IActionResult Index() {
            return View("Index",this._service.ShowBooks());
        }

        [HttpPost]
        public IActionResult AddBook(BookModel newBook) {
            this._service.AddBook(newBook);
            return RedirectToAction("Index");
        }

        public IActionResult RemoveBook(int removedBook) {
            this._service.RemoveBook(removedBook);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ConnectionsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ProjectZero.Models;
using ProjectZero.Services;

namespace ProjectZero.Controllers {
    public class ConnectionsController : Controller {
        private readonly IAuthorService _service1;
        private readonly IBookService _service2;
        private readonly IAuthorBookConnectionService _service3;
        public ConnectionsController (IAuthorService service1, IBookService service2, IAuthorBookConnectionService service3) {
            this._service1 = service1;
            this._service2 = service2;
            this._service3 = service3;
        }

        public IActionResult Index() {
            return View(this._service3.ShowAuthorBookConnections());
        }

        public IActionResult CreateNewConnection() {
            LibraryModel sentList = new LibraryModel();
            sentList.AllTheAuthors = this._service1.ShowAuthors();
            sentList.AllTheBooks = this._service2.ShowBooks();
            return View(sentList);
        }

        [HttpPost]
        public IActionResult AddConnection(int authorId, int bookId) {
            if (this._service3.CheckConnection(authorId, bookId)) {
                Console.WriteLine("This connection already exists");
            }
            else {
                this._service3.AddAuthorBookConnection(authorId, bookId);
            }
            return RedirectToAction("CreateNewConnection");
        }

        public IActionResult RemoveConnection(int rmvConnection) {
            this._service3.RemoveAuthorBookConnection(rmvConnection);
            return RedirectToAction("Index");
        }

        public IActionResult CheckConnection(int givenAuthor, int givenBook) {
            if (this._service3.CheckConnection(givenAuthor, givenBook)) {
                Console.WriteLine("Dot dot doT");
            };
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectZero</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectZero</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Connections" asp-action="Index">Connections</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileExplorerAdmin" asp-controller="Home" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileExplorerUser" asp-controller="Home" asp-action="Index">User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/modal.js" asp-append-version="true"></script>
    <script src="~/js/dragndrop.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>